# config/packages/security.yaml
security:
    role_hierarchy:
        # No direct mapping needed if using roles without the 'ROLE_' prefix

    access_control:
        - { path: ^/back, roles: 'ROLE_administrateur' }

        # Define access controls as per your application's requirements

    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: auto

    providers:
        # Configure your custom user provider to load users from the database
        database_users:
            entity:
                class: App\Entity\User
                property: emailusr

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_users # Use the custom user provider for authentication
            custom_authenticator: App\Security\Authenticator
            # Your other firewall configurations...
